sudo: required

language: java

services:
  - docker
  
before_install:
- docker pull deepnadig/docker-onos-dev
- docker pull onosproject/onos
- docker run -d onosproject/onos
- docker ps -a
- git clone https://git.deepaknadig.com/deepak/OpenSec.git
- cd OpenSec
- export ONOS_WEB_USER=onos
- export ONOS_WEB_PASS=rocks


script:
- mvn clean install
#~ - /root/onos/tools/dev/bin/onos-app 127.0.0.1 install! target/OpenSec-1.0.2.oar
